

ALTER TABLE TB_INSTITUICAO DROP FOREIGN KEY FK_TB_INSTITUICAO_ID_ENDERECO
ALTER TABLE TB_FONE DROP FOREIGN KEY FK_TB_FONE_ID_INSTITUICAO
ALTER TABLE TB_EMAIL DROP FOREIGN KEY FK_TB_EMAIL_ID_INSTITUICAO
ALTER TABLE TB_CURSO DROP FOREIGN KEY FK_TB_CURSO_ID_INSTITUICAO
ALTER TABLE TB_DISCIPLINA DROP FOREIGN KEY FK_TB_DISCIPLINA_ID_DISCIPLINA
ALTER TABLE TB_SALA_DE_CHAT DROP FOREIGN KEY FK_TB_SALA_DE_CHAT_ID_SALA_DE_CHAT
ALTER TABLE TB_CURSO_DISCIPLINA DROP FOREIGN KEY FK_TB_CURSO_DISCIPLINA_ID_CURSO
ALTER TABLE TB_CURSO_DISCIPLINA DROP FOREIGN KEY FK_TB_CURSO_DISCIPLINA_ID_DISCIPLINA
ALTER TABLE TB_DISCIPLINA_ALUNO DROP FOREIGN KEY FK_TB_DISCIPLINA_ALUNO_ID_DISCIPLINA
ALTER TABLE TB_DISCIPLINA_ALUNO DROP FOREIGN KEY FK_TB_DISCIPLINA_ALUNO_ID_ALUNO
ALTER TABLE TB_DISCIPLINA_MONITOR DROP FOREIGN KEY FK_TB_DISCIPLINA_MONITOR_ID_DISCIPLINA
ALTER TABLE TB_DISCIPLINA_MONITOR DROP FOREIGN KEY FK_TB_DISCIPLINA_MONITOR_ID_ALUNO
DROP TABLE TB_INSTITUICAO
DROP TABLE TB_FONE
DROP TABLE TB_ENDERECO
DROP TABLE TB_EMAIL
DROP TABLE TB_CURSO
DROP TABLE TB_DISCIPLINA
DROP TABLE TB_SALA_DE_CHAT
DROP TABLE TB_ALUNO
DROP TABLE TB_PROFESSOR
DROP TABLE TB_ADMINISTRADOR
DROP TABLE TB_CURSO_DISCIPLINA
DROP TABLE TB_DISCIPLINA_ALUNO
DROP TABLE TB_DISCIPLINA_MONITOR
DROP TABLE TB_ENDERECO
CREATE TABLE TB_INSTITUICAO (ID BIGINT AUTO_INCREMENT NOT NULL, TXT_CNPJ VARCHAR(255), TXT_NOME VARCHAR(255), TXT_SIGLA VARCHAR(255), ID_ENDERECO BIGINT, PRIMARY KEY (ID))
CREATE TABLE TB_FONE (ID BIGINT AUTO_INCREMENT NOT NULL, TXT_FONE VARCHAR(255), ID_INSTITUICAO BIGINT, PRIMARY KEY (ID))
CREATE TABLE TB_ENDERECO (ID BIGINT AUTO_INCREMENT NOT NULL, TXT_BAIRRO VARCHAR(255), TXT_CEP VARCHAR(255), TXT_CIDADE VARCHAR(255), TXT_COMPLEMENTO VARCHAR(255), TXT_ESTADO VARCHAR(255), TXT_LOGRADOURO VARCHAR(255), TXT_NUMERO VARCHAR(255), PRIMARY KEY (ID))
CREATE TABLE TB_ENDERECO (ID BIGINT AUTO_INCREMENT NOT NULL, TXT_BAIRRO VARCHAR(255), TXT_CEP VARCHAR(255), TXT_CIDADE VARCHAR(255), TXT_COMPLEMENTO VARCHAR(255), TXT_ESTADO VARCHAR(255), TXT_LOGRADOURO VARCHAR(255), TXT_NUMERO VARCHAR(255), PRIMARY KEY (ID))
CREATE TABLE TB_EMAIL (ID BIGINT AUTO_INCREMENT NOT NULL, TXT_EMAIL VARCHAR(255), ID_INSTITUICAO BIGINT, PRIMARY KEY (ID))
CREATE TABLE TB_CURSO (ID BIGINT AUTO_INCREMENT NOT NULL, TXT_NOME VARCHAR(255), ID_INSTITUICAO BIGINT, PRIMARY KEY (ID))
CREATE TABLE TB_DISCIPLINA (ID BIGINT AUTO_INCREMENT NOT NULL, TXT_NOME VARCHAR(255), ID_DISCIPLINA BIGINT, PRIMARY KEY (ID))
CREATE TABLE TB_SALA_DE_CHAT (ID BIGINT AUTO_INCREMENT NOT NULL, TXT_DESCRICAO VARCHAR(255), ID_SALA_DE_CHAT BIGINT, PRIMARY KEY (ID))
CREATE TABLE TB_ALUNO (ID BIGINT AUTO_INCREMENT NOT NULL, TXT_MATRICULA VARCHAR(255), PRIMARY KEY (ID))
CREATE TABLE TB_PROFESSOR (ID BIGINT AUTO_INCREMENT NOT NULL, PRIMARY KEY (ID))
CREATE TABLE TB_ADMINISTRADOR (ID BIGINT AUTO_INCREMENT NOT NULL, PRIMARY KEY (ID))
CREATE TABLE TB_CURSO_DISCIPLINA (ID_CURSO BIGINT NOT NULL, ID_DISCIPLINA BIGINT NOT NULL, PRIMARY KEY (ID_CURSO, ID_DISCIPLINA))
CREATE TABLE TB_DISCIPLINA_ALUNO (ID_DISCIPLINA BIGINT NOT NULL, ID_ALUNO BIGINT NOT NULL, PRIMARY KEY (ID_DISCIPLINA, ID_ALUNO))
CREATE TABLE TB_DISCIPLINA_MONITOR (ID_DISCIPLINA BIGINT NOT NULL, ID_ALUNO BIGINT NOT NULL, PRIMARY KEY (ID_DISCIPLINA, ID_ALUNO))
ALTER TABLE TB_INSTITUICAO ADD CONSTRAINT FK_TB_INSTITUICAO_ID_ENDERECO FOREIGN KEY (ID_ENDERECO) REFERENCES TB_ENDERECO (ID)
ALTER TABLE TB_FONE ADD CONSTRAINT FK_TB_FONE_ID_INSTITUICAO FOREIGN KEY (ID_INSTITUICAO) REFERENCES TB_INSTITUICAO (ID)
ALTER TABLE TB_EMAIL ADD CONSTRAINT FK_TB_EMAIL_ID_INSTITUICAO FOREIGN KEY (ID_INSTITUICAO) REFERENCES TB_INSTITUICAO (ID)
ALTER TABLE TB_CURSO ADD CONSTRAINT FK_TB_CURSO_ID_INSTITUICAO FOREIGN KEY (ID_INSTITUICAO) REFERENCES TB_INSTITUICAO (ID)
ALTER TABLE TB_DISCIPLINA ADD CONSTRAINT FK_TB_DISCIPLINA_ID_DISCIPLINA FOREIGN KEY (ID_DISCIPLINA) REFERENCES TB_PROFESSOR (ID)
ALTER TABLE TB_SALA_DE_CHAT ADD CONSTRAINT FK_TB_SALA_DE_CHAT_ID_SALA_DE_CHAT FOREIGN KEY (ID_SALA_DE_CHAT) REFERENCES TB_DISCIPLINA (ID)
ALTER TABLE TB_CURSO_DISCIPLINA ADD CONSTRAINT FK_TB_CURSO_DISCIPLINA_ID_CURSO FOREIGN KEY (ID_CURSO) REFERENCES TB_CURSO (ID)
ALTER TABLE TB_CURSO_DISCIPLINA ADD CONSTRAINT FK_TB_CURSO_DISCIPLINA_ID_DISCIPLINA FOREIGN KEY (ID_DISCIPLINA) REFERENCES TB_DISCIPLINA (ID)
ALTER TABLE TB_DISCIPLINA_ALUNO ADD CONSTRAINT FK_TB_DISCIPLINA_ALUNO_ID_DISCIPLINA FOREIGN KEY (ID_DISCIPLINA) REFERENCES TB_DISCIPLINA (ID)
ALTER TABLE TB_DISCIPLINA_ALUNO ADD CONSTRAINT FK_TB_DISCIPLINA_ALUNO_ID_ALUNO FOREIGN KEY (ID_ALUNO) REFERENCES TB_ALUNO (ID)
ALTER TABLE TB_DISCIPLINA_MONITOR ADD CONSTRAINT FK_TB_DISCIPLINA_MONITOR_ID_DISCIPLINA FOREIGN KEY (ID_DISCIPLINA) REFERENCES TB_DISCIPLINA (ID)
ALTER TABLE TB_DISCIPLINA_MONITOR ADD CONSTRAINT FK_TB_DISCIPLINA_MONITOR_ID_ALUNO FOREIGN KEY (ID_ALUNO) REFERENCES TB_ALUNO (ID)